name: List all files
description: List all files using Bash ls command
author: Matheus
runs:
  using: "composite"
  steps: 
    - run: chmod +x ./scripts/list_files.sh
      shell: bash
    - run: ./scripts/list_files.sh
      shell: bash
