name: Call custom actions

on:
  workflow_dispatch:

jobs:  
  call:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Call actions
        uses: ./.github/actions/custom_actions.yaml
