name: Call custom docker action

on: 
    workflow_dispatch:
      inputs:
        top_k:  
          description: 'k largest elementst'
          required: true
          default: 1
env:
    TOP_K: ${{ github.event.inputs.top_k }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: TOP_K
              run: echo 'TOP_K=${{ env.TOP_K }}' >> $GITHUB_OUTPUT
            - name: Call custom docker action
              id: custom_docker
              uses: ./.github/actions/custom_docker
              with:
                top_k: ${{ inputs.top_k }}
              
            - name: Print output
              run: |
               echo "${{ steps.custom_docker.outputs.shape }}"
               echo "${{ steps.custom_docker.outputs.top_k }}"


            - name: Upload Build Artifacts
              uses: actions/upload-artifact@v4
              with:
                name: workspace_artifacts
                path: ${{ github.workspace }}/df.csv
