name: Call custom docker action

on: 
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Call custom docker action
              uses: ./.github/actions/custom_docker