name: CI

# Triggers
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  MY_GLOBAL_ENV_VARIABLE: available_on_all_jobs
jobs:
  # Give job a name
  job-name:
    env:
      MY_JOB_ENV_VARIABLE: job_level_variable
      PORT: 8080
    # Define runner
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello from Actions"
      - name: Get code
        uses: actions/checkout@v4
      - name: Setup python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Cache dependencies for multiple jobs (reduce time)
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip- 
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Print out env variable
        run: echo $PORT
