name: Controlling with if command

on:
  workflow_dispatch:
  
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1
        name: Output
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2      
        name: Step2
        run: echo "test2=hello2" >> "$GITHUB_OUTPUT"
      - name: Run on step2 failure
        if: failure() && steps.step2.outcome == 'failure'
        run: echo "step2 failure"
      - name: Run on step2 success
        if: steps.step2.outcome == 'success'
        run: echo "step2 success"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{ needs.job1.outputs.output1 }}
        run: echo "$OUTPUT1"

  job3: 
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: From job3
        run: echo "Previous job failure"

  job4:
    needs: [job1, job2]
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: From job4
        run: echo "Previous jobs succeed"
    
      
