name: GitHub Actions with Docker

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: alpine:3.20
    steps:
      - name: Build
        run: echo "Building inside Docker container"

