name: GitHub Actions with Docker

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: alpine:3.20
    services:
      qdrant: 
        image: qdrant/qdrant:latest
        volumes:
          - ./qdrant_data:/qdrant/storage
      postgres:
        # Docker Hub image
        image: postgres:16.3
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Build
        run: echo "Building inside Docker container"

