name: GitHub Actions with Docker

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 25
    runs-on: ubuntu-latest
    container: 
      image: alpine:3.20
    steps:
      - name: Build
        run: echo "Building inside Docker container"

