name: Environmental variables

on:
 push:
   branches:
     - main
     - dev
env:
  GLOBAL_VARIABLE: global-variable
  
jobs:
  test1:
    env:
      JOB_1_VARIABLE: job1
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
  test2:
    runs-on: ubuntu-latest
    steps:
      - name: Print Out global variable
        run: echo "Global variable with $ - $GLOBAL_VARIABLE"
      - name: Print out global variable
        run: echo "Global variable  with {{}} - ${{ env.GLOBAL_VARIABLE }}"
      - name: Print out local variable
        run: echo "Global variable with $ - $JOB_1_VARIABLE"
      - name: Print out local variable
        run: echo "Global variable with {{}} - ${{ env.JOB_1_VARIABLE }}"
