name: Assign closed issue label 

on:
  issues:
    types:
      - closed

jobs: 
  assign-label:
    permissions: 
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Assign label
        env:
          ACTOR: ${{ github.actor }}
        run: |
          curl -X POST \
          --url htpps://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          -d '{
                "labels": [ACTOR]
          }' \ 
          --fail
