name: Assign closed issue label

on:
  issues:
    types:
      - closed

jobs: 
  assign-label:
    permissions: 
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Assign label
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels \
          -d '{"labels":["${{ github.actor }}"]}' \
          --fail
