name: 'Output job values'

on:
  workflow_dispatch:
  push: 
    branches: 
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs: 
      script-file: ${{ steps.output_files.outputs.script-file }}
      output1: ${{ steps.step1.test }}
      output2: ${{ steps.step2.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
      - name: Output a value
        id: output_files
        run: find src/*.py -type f -execdir echo "script-file={}" >> $GITHUB_OUTPUT ';'
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{ needs.job1.outputs.output1 }}
          OUTPUT2: ${{ needs.job1.outputs.output2 }}
        run: echo "$OUTPUT1 $OUTPUT2"
