name: Reusable workflow

on: 
  workflow_call:
    inputs:
      s3_bucket_name:
        description: The name of the S3 bucket where the model will be uploaded
        type: string
        required: true
        default: models
    #secrets:
      #aws_secret:
        #description: The AWS secret
        #required: true
    outputs:
      status: 
        description: The status of the deployment
        value: ${{ jobs.deploy.outputs.status }}
        
jobs:
  deploy:
    outputs:
      status: ${{ steps.status.outputs.status }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying to s3 directory - ${{ inputs.s3_bucket_name }}"
      - name: Status
        id: status
        run: echo "status=success" >> "$GITHUB_OUTPUT"
